sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t kiararip/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kiararip/docker-react npm run test

deploy:
  # edge: true
  provider: elasticbeanstalk
  app: "docker-react"
  region: "us-west-2"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-844536310388"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
